
name: Docker Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u morevi -p $DOCKER_PASS
      - name: docker build
        run: |
          docker build . --tag morevi/getitdone:tests
      - name: docker push
        run: |
          docker push morevi/getitdone:tests

