
name: Deploy on Vercel
on:
  workflow_run:
    workflows: ["dbt"]
    branches: ["master"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        # Trigger VERCEL API
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_TRIGGER }}
