name: Docker Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build . --tag morevi/getitdone
      - name: docker test
        run: |
          docker run --rm morevi/getitdone
      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u morevi -p $DOCKER_PASS
      - name: docker push
          docker push morevi/getitdone
