name: Docker Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build . --tag morevi/getitdone
      - name: docker test
        run: |
          docker run --rm morevi/getitdone
          
      # DOCKER HUB
      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: docker push to dockerhub
        run: |
          docker push morevi/getitdone
          
      # GITHUB CONTAINER REGISTRY
      - name: ghcr login
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_PASS }}
          registry: ghcr.io
      - name: docker push to ghcr
        run: |
          docker tag morevi/getitdone ghcr.io/morevi/getitdone:latest
          docker push ghcr.io/morevi/getitdone:latest

