name: docker-build

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.container }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        name: Comprobando Dockerfile
        id: changes
        with:
          filters: |
            container:
              - 'Dockerfile'

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: |
          make docker-build

      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: docker push to dockerhub
        run: |
          make docker-push
