name: docker-build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        name: Comprobando Dockerfile
        id: changes
        with:
          filters: |
            container:
              - 'Dockerfile'

      - name: docker build
        if: steps.check-files.output.changed
        run: |
          docker build . --tag morevi/getitdone:latest

      - name: dockerhub login
        if: steps.check-files.output.changed
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: docker push to dockerhub
        if: steps.check-files.output.changed
        run: |
          docker push morevi/getitdone:latest

      - name: docker test
        run: |
          docker run -t -v `pwd`:/test morevi/getitdone:latest 
