name: Docker Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build . --tag morevi/getitdone
      - name: docker test
        run: |
          docker run --rm morevi/getitdone
          
  push-dockerhub:
    runs-on: ubuntu-latest
    needs: build-test
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: docker push
        run: |
          docker push morevi/getitdone
          
  push-ghcr:
    runs-on: ubuntu-latest
    needs: build-test
    
      - name: ghcr login
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASS }}
          registry: ghcr.io
