name: run-tests

on:
  workflow_run:
    workflows: "docker-build"
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run tests 
        run: make docker-test



